#!/bin/sh
 echo " ----- script de control para emu oscam -----" 

  while [ 1 ] ; do
  pidof oscam >/dev/null
  if [ $? -eq 0 ] ; then
    echo " OK"
  else
    DATE=$(date) 
    echo "Restarting oscam : " >> /tmp/check_oscam.log
    /usr/CamEmu/camemu.oscam restart
 fi

 sleep 60
 done
